#!/usr/bin/zsh

startup () {
	# info on any running screens
	if [[ -x $(which screen) ]]
	then
		ZSHRC_SCREENLIST=(${${(M)${(f)"$(screen -ls)"}:#(#s)[[:space:]]##([0-9]##).*}/(#b)[[:space:]]#([0-9]##).*/$match[1]})
		if [[ $#ZSHRC_SCREENLIST -ge 1 ]]
		then
			echo "There are $#ZSHRC_SCREENLIST screens running. $ZSHRC_SCREENLIST"
		fi
	fi

## TODO: Change to check /sys and build in rebuildrprompt()
##       maybe use /sys directly, if possible
#	# check if acpitool is installed. if yes, tell rebuildrprompt to use it
#	if [[ -x $(which acpitool) ]]
#	then
#		ZSHRC_ACPITOOL='1'
#	fi

	startup_warnings

	buildPS1


	# change the terminals title if it's a xterm, konsole or the like
	header "%l %n@%m: %~"
}

