#!/usr/bin/zsh

##TODO: find out how to access the keys of the assoc array & display that instead of XXX

zshrc_show_colors() {
	autoload colors
	colors

	foreach test ($fg_no_bold); do; print -nP "$test""XXX "; done; echo
	foreach test ($fg_bold);    do; print -nP "$test""XXX "; done; echo
	print -nP "$fg[default]"
	foreach test ($bg_no_bold); do; print -nP "$test""XXX$bg[default] "; done; echo
	foreach test ($bg_bold);    do; print -nP "$test""XXX$bg[default] "; done; echo

}

#fg_green=$'%{\e[32m%}'
#fg_blue=$'%{\e[34m%}'
#fg_cyan=$'%{\e[36m%}'
#fg_red=$'%{\e[31m%}'
#fg_brown=$'%{\e[33m%}'
#fg_purple=$'%{\e[35m%}'
#
#fg_light_gray=$'%{\e[1;37m%}'
#fg_dark_gray=$'%{\e[1;30m%}'
#fg_light_blue=$'%{\e[1;34m%}'
#fg_light_yellow=$'%{\e[1;33m%}'
#fg_light_green=$'%{\e[1;32m%}'
#fg_light_cyan=$'%{\e[1;36m%}'
#fg_light_red=$'%{\e[1;31m%}'
#fg_light_purple=$'%{\e[1;35m%}'
#fg_no_colour=$'%{\e[0m%}'
#
#fg_white=$'%{\e[37m%}'
#fg_black=$'%{\e[30m%}'
#
#col_inverted=$'%{\e[1;7m%}'

#	print -nP "$fg_green gr $fg_blue bl $fg_cyan cy $fg_red re $fg_brown br $fg_purple pu $fg_light_gray lg $fg_dark_gray dg $fg_light_blue lb $fg_light_green lg $fg_light_cyan lc $fg_light_purple lp $fg_no_colour nc $fg_white wh $fg_black bl $fg_no_colour \n"
